version: '3.9'

services:
  devcontainer:
    build: .
    volumes:
      - ../.:/workspace:cached
      - ~/.ssh:/root/.ssh:cached
    ports:
      - 9876:9876
      - 4200:4200
    command: sleep infinity
    